/**
 * Copyright (c) 2024 OceanBase
 * OceanBase Migration Service LogProxy is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan PubL v2.
 * You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#include <bitset>
#include "gtest/gtest.h"
#ifndef BUILD_OPENSOURCE
#include "binlog/ddl-parser/ddl_parser.h"

using namespace oceanbase::logproxy;

TEST(DDLParser, init)
{
  oceanbase::binlog::DdlParser sql_parser;
  Config::instance().binlog_ddl_convert_jvm_options.set(
      "-Djava.class.path=./deps/lib/"
      "etransfer.jar|-Xmx256M|-Xtrace|-XX:+CreateMinidumpOnCrash|-verbose:jni");
  sql_parser.init();
  std::string origin =
      "CREATE TABLE `bank_business_table`\n"
      "(\n"
      "    `MAIN_CUST_INR_ID`         char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '主客户内部编号',\n"
      "    `TXN_INR_ID`               varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT "
      "'交易内部编号',\n"
      "    `MAIN_TXN_INR_ID`          varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '主交易内部编号',\n"
      "    `BSN_LYR_ACCT_NO`          varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '业务层账号',\n"
      "    `CYC_NO`                   int(11) DEFAULT NULL COMMENT '周期号',\n"
      "    `TXN_SEQ_NO`               int(11) DEFAULT NULL COMMENT '交易序号',\n"
      "    `CUST_INR_ID`              varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '客户内部编号',\n"
      "    `CARD_NO`                  varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '卡号',\n"
      "    `PRCIP_ADCRD_FLG`          char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '主附卡标志',\n"
      "    `BSN_TP_CD`                varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '业务类型代码',\n"
      "    `BSN_UNIT_NO`              varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '业务单元号',\n"
      "    `BAL_OBJ_CD`               varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '余额对象代码',\n"
      "    `BAL_OBJ_TP_CD`            char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '余额对象类型代码',\n"
      "    `POST_TXN_CD`              varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '入账交易码',\n"
      "    `POST_DT`                  char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '入账日期',\n"
      "    `POST_TME`                 char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '入账时间',\n"
      "    `POST_AMT`                 decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '入账金额',\n"
      "    `POST_CCY_CD`              char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '入账币种代码',\n"
      "    `POST_CCY_DECI_DGT_VAL`    int(2) DEFAULT NULL COMMENT '入账币种小数位',\n"
      "    `TXN_DTE`                  char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '交易日期',\n"
      "    `TXN_TME`                  char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '交易时间',\n"
      "    `TXN_AMT`                  decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '交易金额',\n"
      "    `TXN_CCY_CD`               varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易币种代码',\n"
      "    `TXNCCY_DECI_DGT_VAL`      int(2) DEFAULT NULL COMMENT '交易货币小数位',\n"
      "    `CLRG_AMT`                 decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '清算金额',\n"
      "    `CLRG_CCY_CD`              char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '清算币种代码',\n"
      "    `CLRG_CCY_DECI_DGT_VAL`    int(2) DEFAULT NULL COMMENT '清算币种小数位',\n"
      "    `DEBIT_CDT_TP`             char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '借贷类型',\n"
      "    `CDCRD_CORE_TXN_CATG`      varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '贷记卡核心交易大类',\n"
      "    `SHOW_TO_CUST_FLG`         char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '对客展示标志',\n"
      "    `TXN_POST_MODE_CD`         varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易入账模式代码',\n"
      "    `DOM_OVS_FLG_CD`           varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '境内外类型代码',\n"
      "    `CRD_ORG_CHNL_CD`          varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '卡组织渠道代码',\n"
      "    `CHNL_TXN_SER_NO`          varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '渠道交易流水号',\n"
      "    `ATH_TXN_SER_NO`           varchar(31) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '授权交易流水号',\n"
      "    `PENDG_POST_ATH_INR_ID`    varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '待入账授权内部编号',\n"
      "    `ATH_MSG_TP_CD`            varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '授权消息类型代码',\n"
      "    `TXN_STS_CD`               varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易状态代码',\n"
      "    `TXN_DES`                  varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin         DEFAULT NULL "
      "COMMENT '交易描述',\n"
      "    `OGLTXN_INR_ID`            varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '原交易内部编号',\n"
      "    `RLT_CDT_TXN_INR_ID`       varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联贷记交易内部编号',\n"
      "    `RLT_INSTM_TXN_INR_ID`     varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联分期交易内部编号',\n"
      "    `RLT_DISPT_TXN_INR_ID`     varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联争议交易内部编号',\n"
      "    `RLT_ON_ACCT_TXN_INR_ID`   varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联悬挂账交易内部编号',\n"
      "    `RLT_CCY_EXCH_FEE_INR_ID`  varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联货币兑换手续费内部编号',\n"
      "    `RLT_HDL_FEE_INR_ID`       varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联手续费内部编号',\n"
      "    `ORGL_CHNL_TXN_SER_NO`     varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '原渠道交易流水号',\n"
      "    `ORGL_ATH_TXN_SER_NO`      varchar(31) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '原授权交易流水号',\n"
      "    `DEBIT_ACRUD_AMT`          decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '借方发生额',\n"
      "    `CDT_ACRUD_AMT`            decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '贷方发生额',\n"
      "    `CDT_ADJ_AMT`              decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '贷方调整金额',\n"
      "    `BLUNIT_ASGN_LIST`         text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'余额单元分配列表',\n"
      "    `WTEDOW_MINDUE_AMT_AMT`    decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '冲减最低应付款金额',\n"
      "    `TXN_INS_REDU_ACTY_CD`     varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易立减活动代码',\n"
      "    `BEF_INS_REDU_AMT`         decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '立减前金额',\n"
      "    `INS_REDU_AMT`             decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '立减金额',\n"
      "    `RMNG_SBSD_AMT`            decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '剩余补贴金额',\n"
      "    `RTN_INS_REDU_SBSD_AMT`    decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '扣回立减补贴金额',\n"
      "    `AUTO_BUY_EXCH_EXCH_RTE`   decimal(9, 5)                                                  DEFAULT NULL "
      "COMMENT '自动购汇汇率',\n"
      "    `EXCH_STLMT_AMT`           decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '已结汇金额',\n"
      "    `INSTM_SCSS_FLG`           char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '分期成功标志',\n"
      "    `INSTM_PROD_CD`            varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '分期产品代码',\n"
      "    `INSTM_AMT`                decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '分期金额',\n"
      "    `INSTM_ORG_CD`             char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '分期组织代码',\n"
      "    `OTH_CLRG_MATCH_CRITR`     varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '其他清算匹配准则',\n"
      "    `GMT_FMT_DT_AND_TME`       varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT 'GMT格式的日期和时间',\n"
      "    `ATH_DT`                   char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '授权日期',\n"
      "    `ATH_TME`                  char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '授权时间',\n"
      "    `TXN_ATH_ENCDE`            varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易授权码',\n"
      "    `MCC`                      varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '商户类别代码',\n"
      "    `TXN_CTRY_CD`              char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '交易国家代码',\n"
      "    `TXN_CITY_CD`              varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易城市代码',\n"
      "    `TXN_CHNL_CD`              varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易渠道代码',\n"
      "    `MEDM_PROD_CD`             varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '介质产品代码',\n"
      "    `ASSET_ATTR_CD`            varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT '0' "
      "COMMENT '资产属性代码',\n"
      "    `SERH_REF_NO`              varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '检索参考号',\n"
      "    `CLOUD_CRD_NO`             varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '云卡卡号',\n"
      "    `CUP_MCC_SPCL_CRG_CD`      varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '银联MCC特殊计费代码',\n"
      "    `MICRO_EXMT_PSWD_FLG`      char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '小额免密标志',\n"
      "    `QR_CD_SCNE_TP_CD`         char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '二维码场景类型代码',\n"
      "    `CNTPR_FIN_INST_BCHNW_CD`  varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '对方金融机构网点代码',\n"
      "    `CTP_FININST_BCHNW_NME`    varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin         DEFAULT NULL "
      "COMMENT '对方金融机构网点名称',\n"
      "    `CNTPR_NME`                varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易对手名称',\n"
      "    `CNTPR_ACCT_NO`            varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易对手账号',\n"
      "    `CNTPR_ID_TP_CD`           varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易对手证件类型代码',\n"
      "    `CNTPR_ID_NO`              varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易对手证件号码',\n"
      "    `ACCT_CHKG_STAG_CD`        varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '账户核算阶段代码',\n"
      "    `CLCMCTL_FLG`              char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '催收管控标志',\n"
      "    `OVLMT_FLG`                char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '超限标志',\n"
      "    `OVLMT_RSN_CD`             varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '超限原因代码',\n"
      "    `OVLMT_AMT`                decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '超限金额',\n"
      "    `INR_PROD_CD`              varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '内部产品代码',\n"
      "    `RECVG_BCH_NO`             char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '受理分行号',\n"
      "    `EQTY_ID`                  varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '权益编号',\n"
      "    `ATH_MATCH_FLG`            char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '授权匹配标志',\n"
      "    `ACQRR_CD`                 varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '收单机构代码',\n"
      "    `TRMNL_NO`                 varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '终端号',\n"
      "    `PCS_CD`                   varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '处理码',\n"
      "    `SERV_SPOT_INPT_MTHD_CD`   varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '服务点输入方式代码',\n"
      "    `MERCH_ID`                 varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '商户编号',\n"
      "    `LV2_MCC`                  varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '二级商户类别代码',\n"
      "    `LV2_MERCH_ID`             varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '二级商户编号',\n"
      "    `LV2_MERCH_NME`            varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '二级商户名称',\n"
      "    `R36CYC_RPM_HISR`          varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '最近36个周期的还款历史',\n"
      "    `SYS_TRACE_AUDT_NO`        varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '系统追踪审计号',\n"
      "    `ACCT_CLCN_STS_CD`         char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '账户催收状态代码',\n"
      "    `ACCT_PROD_TP_CD`          char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '账产品类型代码',\n"
      "    `ANTI_MNYLADR_SBMSN_FLG`   char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '反洗钱报送标志',\n"
      "    `INTSTL_DAYRPL_BTW_TX_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '结息到日切间交易标志',\n"
      "    `INST_CD`                  char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '机构代码',\n"
      "    `OPRT_ID`                  varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '操作员编号',\n"
      "    `OPR_DT`                   char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '操作日期',\n"
      "    `BTCH_SEQ_NO`              int(6) DEFAULT NULL COMMENT '批次序号',\n"
      "    `OPR_FLG`                  char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin     NOT NULL DEFAULT 'E' "
      "COMMENT '操作标志',\n"
      "    `CRE_TMS`                  datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP (3) COMMENT '创建时间戳',\n"
      "    `CRE_USER_ID`              varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'SYSTEM' "
      "COMMENT '创建用户编号',\n"
      "    `CRE_CHNL_CD`              varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '创建渠道代码',\n"
      "    `UPDT_TMS`                 datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP (3) COMMENT '更新时间戳',\n"
      "    `UPDT_USER_ID`             varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'SYSTEM' "
      "COMMENT '更新用户编号',\n"
      "    `UPDT_CHNL_CD`             varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '变更渠道代码',\n"
      "    `REC_VERSN_NO`             int(8) NOT NULL DEFAULT '0' COMMENT '记录版本号',\n"
      "    PRIMARY KEY (`TXN_INR_ID`),\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_1` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, "
      "`RLT_INSTM_TXN_INR_ID`, `BSN_UNIT_NO`, `POST_DT`, `BAL_OBJ_CD`, `BAL_OBJ_TP_CD`, `DEBIT_CDT_TP`, "
      "`INSTM_SCSS_FLG`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_10` (`POST_DT`, `DEBIT_CDT_TP`, `BSN_TP_CD`, "
      "`DOM_OVS_FLG_CD`, `ATH_MATCH_FLG`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_2` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, `CARD_NO`, "
      "`CYC_NO`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_3` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, `CYC_NO`, "
      "`TXN_SEQ_NO`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_4` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, "
      "`ATH_TXN_SER_NO`, `ACQRR_CD`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_5` (`MAIN_CUST_INR_ID`, `CARD_NO`, `SYS_TRACE_AUDT_NO`, "
      "`ATH_TME`, `ACQRR_CD`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_7` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, `CYC_NO`, "
      "`TXN_STS_CD`, `CARD_NO`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_8` (`POST_DT`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_9` (`MAIN_CUST_INR_ID`, `CUST_INR_ID`, "
      "`PENDG_POST_ATH_INR_ID`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_11` (`CHNL_TXN_SER_NO`) BLOCK_SIZE 16384 LOCAL\n"
      ") DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 3 BLOCK_SIZE = 16384 "
      "USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0\n"
      " partition by key(txn_inr_id)\n"
      "(partition p0,\n"
      "partition p1,\n"
      "partition p2,\n"
      "partition p3,\n"
      "partition p4,\n"
      "partition p5,\n"
      "partition p6,\n"
      "partition p7,\n"
      "partition p8,\n"
      "partition p9,\n"
      "partition p10,\n"
      "partition p11,\n"
      "partition p12,\n"
      "partition p13,\n"
      "partition p14,\n"
      "partition p15,\n"
      "partition p16,\n"
      "partition p17,\n"
      "partition p18,\n"
      "partition p19,\n"
      "partition p20,\n"
      "partition p21,\n"
      "partition p22,\n"
      "partition p23,\n"
      "partition p24,\n"
      "partition p25,\n"
      "partition p26,\n"
      "partition p27,\n"
      "partition p28,\n"
      "partition p29,\n"
      "partition p30,\n"
      "partition p31,\n"
      "partition p32,\n"
      "partition p33,\n"
      "partition p34,\n"
      "partition p35,\n"
      "partition p36,\n"
      "partition p37,\n"
      "partition p38,\n"
      "partition p39,\n"
      "partition p40,\n"
      "partition p41,\n"
      "partition p42,\n"
      "partition p43,\n"
      "partition p44,\n"
      "partition p45,\n"
      "partition p46,\n"
      "partition p47,\n"
      "partition p48,\n"
      "partition p49,\n"
      "partition p50,\n"
      "partition p51,\n"
      "partition p52,\n"
      "partition p53,\n"
      "partition p54,\n"
      "partition p55,\n"
      "partition p56,\n"
      "partition p57,\n"
      "partition p58,\n"
      "partition p59,\n"
      "partition p60,\n"
      "partition p61,\n"
      "partition p62,\n"
      "partition p63,\n"
      "partition p64,\n"
      "partition p65,\n"
      "partition p66,\n"
      "partition p67,\n"
      "partition p68,\n"
      "partition p69,\n"
      "partition p70,\n"
      "partition p71,\n"
      "partition p72,\n"
      "partition p73,\n"
      "partition p74,\n"
      "partition p75,\n"
      "partition p76,\n"
      "partition p77,\n"
      "partition p78,\n"
      "partition p79,\n"
      "partition p80,\n"
      "partition p81,\n"
      "partition p82,\n"
      "partition p83,\n"
      "partition p84,\n"
      "partition p85,\n"
      "partition p86,\n"
      "partition p87,\n"
      "partition p88,\n"
      "partition p89,\n"
      "partition p90,\n"
      "partition p91,\n"
      "partition p92,\n"
      "partition p93,\n"
      "partition p94,\n"
      "partition p95,\n"
      "partition p96,\n"
      "partition p97,\n"
      "partition p98,\n"
      "partition p99,\n"
      "partition p100,\n"
      "partition p101,\n"
      "partition p102,\n"
      "partition p103,\n"
      "partition p104,\n"
      "partition p105,\n"
      "partition p106,\n"
      "partition p107,\n"
      "partition p108,\n"
      "partition p109,\n"
      "partition p110,\n"
      "partition p111,\n"
      "partition p112,\n"
      "partition p113,\n"
      "partition p114,\n"
      "partition p115,\n"
      "partition p116,\n"
      "partition p117,\n"
      "partition p118,\n"
      "partition p119,\n"
      "partition p120,\n"
      "partition p121,\n"
      "partition p122,\n"
      "partition p123,\n"
      "partition p124,\n"
      "partition p125,\n"
      "partition p126,\n"
      "partition p127);";
  std::string result;
  sql_parser.parse(origin, result);
  std::string excepted =
      "CREATE TABLE `bank_business_table`(\n"
      "\t`MAIN_CUST_INR_ID` CHAR (20) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '主客户内部编号',\n"
      "\t`TXN_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin NOT NULL  COMMENT '交易内部编号',\n"
      "\t`MAIN_TXN_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '主交易内部编号',\n"
      "\t`BSN_LYR_ACCT_NO` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务层账号',\n"
      "\t`CYC_NO` INTEGER (11) DEFAULT NULL COMMENT '周期号',\n"
      "\t`TXN_SEQ_NO` INTEGER (11) DEFAULT NULL COMMENT '交易序号',\n"
      "\t`CUST_INR_ID` VARCHAR (20) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '客户内部编号',\n"
      "\t`CARD_NO` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '卡号',\n"
      "\t`PRCIP_ADCRD_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '主附卡标志',\n"
      "\t`BSN_TP_CD` VARCHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务类型代码',\n"
      "\t`BSN_UNIT_NO` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务单元号',\n"
      "\t`BAL_OBJ_CD` VARCHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '余额对象代码',\n"
      "\t`BAL_OBJ_TP_CD` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '余额对象类型代码',\n"
      "\t`POST_TXN_CD` VARCHAR (6) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '入账交易码',\n"
      "\t`POST_DT` CHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '入账日期',\n"
      "\t`POST_TME` CHAR (8) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '入账时间',\n"
      "\t`POST_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '入账金额',\n"
      "\t`POST_CCY_CD` CHAR (3) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '入账币种代码',\n"
      "\t`POST_CCY_DECI_DGT_VAL` INTEGER (2) DEFAULT NULL COMMENT '入账币种小数位',\n"
      "\t`TXN_DTE` CHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易日期',\n"
      "\t`TXN_TME` CHAR (8) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易时间',\n"
      "\t`TXN_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '交易金额',\n"
      "\t`TXN_CCY_CD` VARCHAR (3) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易币种代码',\n"
      "\t`TXNCCY_DECI_DGT_VAL` INTEGER (2) DEFAULT NULL COMMENT '交易货币小数位',\n"
      "\t`CLRG_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '清算金额',\n"
      "\t`CLRG_CCY_CD` CHAR (3) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '清算币种代码',\n"
      "\t`CLRG_CCY_DECI_DGT_VAL` INTEGER (2) DEFAULT NULL COMMENT '清算币种小数位',\n"
      "\t`DEBIT_CDT_TP` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '借贷类型',\n"
      "\t`CDCRD_CORE_TXN_CATG` VARCHAR (20) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'贷记卡核心交易大类',\n"
      "\t`SHOW_TO_CUST_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '对客展示标志',\n"
      "\t`TXN_POST_MODE_CD` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易入账模式代码',\n"
      "\t`DOM_OVS_FLG_CD` VARCHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '境内外类型代码',\n"
      "\t`CRD_ORG_CHNL_CD` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '卡组织渠道代码',\n"
      "\t`CHNL_TXN_SER_NO` VARCHAR (32) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '渠道交易流水号',\n"
      "\t`ATH_TXN_SER_NO` VARCHAR (31) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '授权交易流水号',\n"
      "\t`PENDG_POST_ATH_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'待入账授权内部编号',\n"
      "\t`ATH_MSG_TP_CD` VARCHAR (20) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '授权消息类型代码',\n"
      "\t`TXN_STS_CD` VARCHAR (6) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易状态代码',\n"
      "\t`TXN_DES` VARCHAR (200) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易描述',\n"
      "\t`OGLTXN_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '原交易内部编号',\n"
      "\t`RLT_CDT_TXN_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'关联贷记交易内部编号',\n"
      "\t`RLT_INSTM_TXN_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'关联分期交易内部编号',\n"
      "\t`RLT_DISPT_TXN_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'关联争议交易内部编号',\n"
      "\t`RLT_ON_ACCT_TXN_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'关联悬挂账交易内部编号',\n"
      "\t`RLT_CCY_EXCH_FEE_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'关联货币兑换手续费内部编号',\n"
      "\t`RLT_HDL_FEE_INR_ID` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'关联手续费内部编号',\n"
      "\t`ORGL_CHNL_TXN_SER_NO` VARCHAR (32) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'原渠道交易流水号',\n"
      "\t`ORGL_ATH_TXN_SER_NO` VARCHAR (31) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'原授权交易流水号',\n"
      "\t`DEBIT_ACRUD_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '借方发生额',\n"
      "\t`CDT_ACRUD_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '贷方发生额',\n"
      "\t`CDT_ADJ_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '贷方调整金额',\n"
      "\t`BLUNIT_ASGN_LIST` TEXT CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '余额单元分配列表',\n"
      "\t`WTEDOW_MINDUE_AMT_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '冲减最低应付款金额',\n"
      "\t`TXN_INS_REDU_ACTY_CD` VARCHAR (20) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'交易立减活动代码',\n"
      "\t`BEF_INS_REDU_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '立减前金额',\n"
      "\t`INS_REDU_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '立减金额',\n"
      "\t`RMNG_SBSD_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '剩余补贴金额',\n"
      "\t`RTN_INS_REDU_SBSD_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '扣回立减补贴金额',\n"
      "\t`AUTO_BUY_EXCH_EXCH_RTE` DECIMAL (9, 5) DEFAULT NULL COMMENT '自动购汇汇率',\n"
      "\t`EXCH_STLMT_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '已结汇金额',\n"
      "\t`INSTM_SCSS_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '分期成功标志',\n"
      "\t`INSTM_PROD_CD` VARCHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '分期产品代码',\n"
      "\t`INSTM_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '分期金额',\n"
      "\t`INSTM_ORG_CD` CHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '分期组织代码',\n"
      "\t`OTH_CLRG_MATCH_CRITR` VARCHAR (15) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'其他清算匹配准则',\n"
      "\t`GMT_FMT_DT_AND_TME` VARCHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'GMT格式的日期和时间',\n"
      "\t`ATH_DT` CHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '授权日期',\n"
      "\t`ATH_TME` CHAR (8) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '授权时间',\n"
      "\t`TXN_ATH_ENCDE` VARCHAR (6) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易授权码',\n"
      "\t`MCC` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商户类别代码',\n"
      "\t`TXN_CTRY_CD` CHAR (3) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易国家代码',\n"
      "\t`TXN_CITY_CD` VARCHAR (16) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易城市代码',\n"
      "\t`TXN_CHNL_CD` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易渠道代码',\n"
      "\t`MEDM_PROD_CD` VARCHAR (8) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '介质产品代码',\n"
      "\t`ASSET_ATTR_CD` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT '0' COMMENT '资产属性代码',\n"
      "\t`SERH_REF_NO` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '检索参考号',\n"
      "\t`CLOUD_CRD_NO` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '云卡卡号',\n"
      "\t`CUP_MCC_SPCL_CRG_CD` VARCHAR (3) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'银联MCC特殊计费代码',\n"
      "\t`MICRO_EXMT_PSWD_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '小额免密标志',\n"
      "\t`QR_CD_SCNE_TP_CD` CHAR (3) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '二维码场景类型代码',\n"
      "\t`CNTPR_FIN_INST_BCHNW_CD` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'对方金融机构网点代码',\n"
      "\t`CTP_FININST_BCHNW_NME` VARCHAR (100) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'对方金融机构网点名称',\n"
      "\t`CNTPR_NME` VARCHAR (60) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易对手名称',\n"
      "\t`CNTPR_ACCT_NO` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易对手账号',\n"
      "\t`CNTPR_ID_TP_CD` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'交易对手证件类型代码',\n"
      "\t`CNTPR_ID_NO` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易对手证件号码',\n"
      "\t`ACCT_CHKG_STAG_CD` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '账户核算阶段代码',\n"
      "\t`CLCMCTL_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '催收管控标志',\n"
      "\t`OVLMT_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '超限标志',\n"
      "\t`OVLMT_RSN_CD` VARCHAR (2) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '超限原因代码',\n"
      "\t`OVLMT_AMT` DECIMAL (17, 0) DEFAULT NULL COMMENT '超限金额',\n"
      "\t`INR_PROD_CD` VARCHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '内部产品代码',\n"
      "\t`RECVG_BCH_NO` CHAR (3) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '受理分行号',\n"
      "\t`EQTY_ID` VARCHAR (16) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '权益编号',\n"
      "\t`ATH_MATCH_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '授权匹配标志',\n"
      "\t`ACQRR_CD` VARCHAR (30) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收单机构代码',\n"
      "\t`TRMNL_NO` VARCHAR (32) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '终端号',\n"
      "\t`PCS_CD` VARCHAR (6) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '处理码',\n"
      "\t`SERV_SPOT_INPT_MTHD_CD` VARCHAR (12) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'服务点输入方式代码',\n"
      "\t`MERCH_ID` VARCHAR (40) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '商户编号',\n"
      "\t`LV2_MCC` VARCHAR (8) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '二级商户类别代码',\n"
      "\t`LV2_MERCH_ID` VARCHAR (40) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '二级商户编号',\n"
      "\t`LV2_MERCH_NME` VARCHAR (60) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '二级商户名称',\n"
      "\t`R36CYC_RPM_HISR` VARCHAR (36) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'最近36个周期的还款历史',\n"
      "\t`SYS_TRACE_AUDT_NO` VARCHAR (6) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '系统追踪审计号',\n"
      "\t`ACCT_CLCN_STS_CD` CHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '账户催收状态代码',\n"
      "\t`ACCT_PROD_TP_CD` CHAR (2) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '账产品类型代码',\n"
      "\t`ANTI_MNYLADR_SBMSN_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '反洗钱报送标志',\n"
      "\t`INTSTL_DAYRPL_BTW_TX_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'结息到日切间交易标志',\n"
      "\t`INST_CD` CHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '机构代码',\n"
      "\t`OPRT_ID` VARCHAR (20) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作员编号',\n"
      "\t`OPR_DT` CHAR (10) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '操作日期',\n"
      "\t`BTCH_SEQ_NO` INTEGER (6) DEFAULT NULL COMMENT '批次序号',\n"
      "\t`OPR_FLG` CHAR (1) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'E' NOT NULL  COMMENT '操作标志',\n"
      "\t`CRE_TMS` DATETIME (3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL  COMMENT '创建时间戳',\n"
      "\t`CRE_USER_ID` VARCHAR (20) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'SYSTEM' NOT NULL  COMMENT "
      "'创建用户编号',\n"
      "\t`CRE_CHNL_CD` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '创建渠道代码',\n"
      "\t`UPDT_TMS` DATETIME (3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL  COMMENT '更新时间戳',\n"
      "\t`UPDT_USER_ID` VARCHAR (20) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'SYSTEM' NOT NULL  COMMENT "
      "'更新用户编号',\n"
      "\t`UPDT_CHNL_CD` VARCHAR (4) CHARSET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '变更渠道代码',\n"
      "\t`REC_VERSN_NO` INTEGER (8) DEFAULT '0' NOT NULL  COMMENT '记录版本号',\n"
      "\tPRIMARY KEY (`TXN_INR_ID`),\n"
      "\tINDEX "
      "`ac_txn_sumry_tmp_ix_1`(`MAIN_CUST_INR_ID`,`BSN_LYR_ACCT_NO`,`RLT_INSTM_TXN_INR_ID`,`BSN_UNIT_NO`,`POST_DT`,`"
      "BAL_OBJ_CD`,`BAL_OBJ_TP_CD`,`DEBIT_CDT_TP`,`INSTM_SCSS_FLG`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_10`(`POST_DT`,`DEBIT_CDT_TP`,`BSN_TP_CD`,`DOM_OVS_FLG_CD`,`ATH_MATCH_FLG`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_2`(`MAIN_CUST_INR_ID`,`BSN_LYR_ACCT_NO`,`CARD_NO`,`CYC_NO`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_3`(`MAIN_CUST_INR_ID`,`BSN_LYR_ACCT_NO`,`CYC_NO`,`TXN_SEQ_NO`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_4`(`MAIN_CUST_INR_ID`,`BSN_LYR_ACCT_NO`,`ATH_TXN_SER_NO`,`ACQRR_CD`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_5`(`MAIN_CUST_INR_ID`,`CARD_NO`,`SYS_TRACE_AUDT_NO`,`ATH_TME`,`ACQRR_CD`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_7`(`MAIN_CUST_INR_ID`,`BSN_LYR_ACCT_NO`,`CYC_NO`,`TXN_STS_CD`,`CARD_NO`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_8`(`POST_DT`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_9`(`MAIN_CUST_INR_ID`,`CUST_INR_ID`,`PENDG_POST_ATH_INR_ID`) ,\n"
      "\tINDEX `ac_txn_sumry_tmp_ix_11`(`CHNL_TXN_SER_NO`) \n"
      ") CHARACTER SET = utf8mb4 PARTITION BY KEY (`txn_inr_id`) \n"
      "(\n"
      "\tPARTITION `p0`,\n"
      "\tPARTITION `p1`,\n"
      "\tPARTITION `p2`,\n"
      "\tPARTITION `p3`,\n"
      "\tPARTITION `p4`,\n"
      "\tPARTITION `p5`,\n"
      "\tPARTITION `p6`,\n"
      "\tPARTITION `p7`,\n"
      "\tPARTITION `p8`,\n"
      "\tPARTITION `p9`,\n"
      "\tPARTITION `p10`,\n"
      "\tPARTITION `p11`,\n"
      "\tPARTITION `p12`,\n"
      "\tPARTITION `p13`,\n"
      "\tPARTITION `p14`,\n"
      "\tPARTITION `p15`,\n"
      "\tPARTITION `p16`,\n"
      "\tPARTITION `p17`,\n"
      "\tPARTITION `p18`,\n"
      "\tPARTITION `p19`,\n"
      "\tPARTITION `p20`,\n"
      "\tPARTITION `p21`,\n"
      "\tPARTITION `p22`,\n"
      "\tPARTITION `p23`,\n"
      "\tPARTITION `p24`,\n"
      "\tPARTITION `p25`,\n"
      "\tPARTITION `p26`,\n"
      "\tPARTITION `p27`,\n"
      "\tPARTITION `p28`,\n"
      "\tPARTITION `p29`,\n"
      "\tPARTITION `p30`,\n"
      "\tPARTITION `p31`,\n"
      "\tPARTITION `p32`,\n"
      "\tPARTITION `p33`,\n"
      "\tPARTITION `p34`,\n"
      "\tPARTITION `p35`,\n"
      "\tPARTITION `p36`,\n"
      "\tPARTITION `p37`,\n"
      "\tPARTITION `p38`,\n"
      "\tPARTITION `p39`,\n"
      "\tPARTITION `p40`,\n"
      "\tPARTITION `p41`,\n"
      "\tPARTITION `p42`,\n"
      "\tPARTITION `p43`,\n"
      "\tPARTITION `p44`,\n"
      "\tPARTITION `p45`,\n"
      "\tPARTITION `p46`,\n"
      "\tPARTITION `p47`,\n"
      "\tPARTITION `p48`,\n"
      "\tPARTITION `p49`,\n"
      "\tPARTITION `p50`,\n"
      "\tPARTITION `p51`,\n"
      "\tPARTITION `p52`,\n"
      "\tPARTITION `p53`,\n"
      "\tPARTITION `p54`,\n"
      "\tPARTITION `p55`,\n"
      "\tPARTITION `p56`,\n"
      "\tPARTITION `p57`,\n"
      "\tPARTITION `p58`,\n"
      "\tPARTITION `p59`,\n"
      "\tPARTITION `p60`,\n"
      "\tPARTITION `p61`,\n"
      "\tPARTITION `p62`,\n"
      "\tPARTITION `p63`,\n"
      "\tPARTITION `p64`,\n"
      "\tPARTITION `p65`,\n"
      "\tPARTITION `p66`,\n"
      "\tPARTITION `p67`,\n"
      "\tPARTITION `p68`,\n"
      "\tPARTITION `p69`,\n"
      "\tPARTITION `p70`,\n"
      "\tPARTITION `p71`,\n"
      "\tPARTITION `p72`,\n"
      "\tPARTITION `p73`,\n"
      "\tPARTITION `p74`,\n"
      "\tPARTITION `p75`,\n"
      "\tPARTITION `p76`,\n"
      "\tPARTITION `p77`,\n"
      "\tPARTITION `p78`,\n"
      "\tPARTITION `p79`,\n"
      "\tPARTITION `p80`,\n"
      "\tPARTITION `p81`,\n"
      "\tPARTITION `p82`,\n"
      "\tPARTITION `p83`,\n"
      "\tPARTITION `p84`,\n"
      "\tPARTITION `p85`,\n"
      "\tPARTITION `p86`,\n"
      "\tPARTITION `p87`,\n"
      "\tPARTITION `p88`,\n"
      "\tPARTITION `p89`,\n"
      "\tPARTITION `p90`,\n"
      "\tPARTITION `p91`,\n"
      "\tPARTITION `p92`,\n"
      "\tPARTITION `p93`,\n"
      "\tPARTITION `p94`,\n"
      "\tPARTITION `p95`,\n"
      "\tPARTITION `p96`,\n"
      "\tPARTITION `p97`,\n"
      "\tPARTITION `p98`,\n"
      "\tPARTITION `p99`,\n"
      "\tPARTITION `p100`,\n"
      "\tPARTITION `p101`,\n"
      "\tPARTITION `p102`,\n"
      "\tPARTITION `p103`,\n"
      "\tPARTITION `p104`,\n"
      "\tPARTITION `p105`,\n"
      "\tPARTITION `p106`,\n"
      "\tPARTITION `p107`,\n"
      "\tPARTITION `p108`,\n"
      "\tPARTITION `p109`,\n"
      "\tPARTITION `p110`,\n"
      "\tPARTITION `p111`,\n"
      "\tPARTITION `p112`,\n"
      "\tPARTITION `p113`,\n"
      "\tPARTITION `p114`,\n"
      "\tPARTITION `p115`,\n"
      "\tPARTITION `p116`,\n"
      "\tPARTITION `p117`,\n"
      "\tPARTITION `p118`,\n"
      "\tPARTITION `p119`,\n"
      "\tPARTITION `p120`,\n"
      "\tPARTITION `p121`,\n"
      "\tPARTITION `p122`,\n"
      "\tPARTITION `p123`,\n"
      "\tPARTITION `p124`,\n"
      "\tPARTITION `p125`,\n"
      "\tPARTITION `p126`,\n"
      "\tPARTITION `p127`\n"
      ")";
  ASSERT_EQ(excepted, result);
}

TEST(DDLParser, failed)
{
  oceanbase::binlog::DdlParser sql_parser;
  Config::instance().binlog_ddl_convert_jvm_options.set("-Djava.class.path=./deps/lib/"
                                                        "etransfer.jar|-Xmx256M|-Xtrace|-XX:+CreateMinidumpOnCrash");
  sql_parser.init();
  std::string origin =
      "CREATE TABLE `bank_business_table`\n"
      "(\n"
      "    `MAIN_CUST_INR_ID`         char(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '主客户内部编号',\n"
      "    `TXN_INR_ID`               varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT "
      "'交易内部编号',\n"
      "    `MAIN_TXN_INR_ID`          varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '主交易内部编号',\n"
      "    `BSN_LYR_ACCT_NO`          varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '业务层账号',\n"
      "    `CYC_NO`                   int(11) DEFAULT NULL COMMENT '周期号',\n"
      "    `TXN_SEQ_NO`               int(11) DEFAULT NULL COMMENT '交易序号',\n"
      "    `CUST_INR_ID`              varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '客户内部编号',\n"
      "    `CARD_NO`                  varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '卡号',\n"
      "    `PRCIP_ADCRD_FLG`          char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '主附卡标志',\n"
      "    `BSN_TP_CD`                varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '业务类型代码',\n"
      "    `BSN_UNIT_NO`              varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '业务单元号',\n"
      "    `BAL_OBJ_CD`               varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '余额对象代码',\n"
      "    `BAL_OBJ_TP_CD`            char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '余额对象类型代码',\n"
      "    `POST_TXN_CD`              varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '入账交易码',\n"
      "    `POST_DT`                  char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '入账日期',\n"
      "    `POST_TME`                 char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '入账时间',\n"
      "    `POST_AMT`                 decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '入账金额',\n"
      "    `POST_CCY_CD`              char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '入账币种代码',\n"
      "    `POST_CCY_DECI_DGT_VAL`    int(2) DEFAULT NULL COMMENT '入账币种小数位',\n"
      "    `TXN_DTE`                  char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '交易日期',\n"
      "    `TXN_TME`                  char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '交易时间',\n"
      "    `TXN_AMT`                  decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '交易金额',\n"
      "    `TXN_CCY_CD`               varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易币种代码',\n"
      "    `TXNCCY_DECI_DGT_VAL`      int(2) DEFAULT NULL COMMENT '交易货币小数位',\n"
      "    `CLRG_AMT`                 decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '清算金额',\n"
      "    `CLRG_CCY_CD`              char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '清算币种代码',\n"
      "    `CLRG_CCY_DECI_DGT_VAL`    int(2) DEFAULT NULL COMMENT '清算币种小数位',\n"
      "    `DEBIT_CDT_TP`             char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '借贷类型',\n"
      "    `CDCRD_CORE_TXN_CATG`      varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '贷记卡核心交易大类',\n"
      "    `SHOW_TO_CUST_FLG`         char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '对客展示标志',\n"
      "    `TXN_POST_MODE_CD`         varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易入账模式代码',\n"
      "    `DOM_OVS_FLG_CD`           varchar(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '境内外类型代码',\n"
      "    `CRD_ORG_CHNL_CD`          varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '卡组织渠道代码',\n"
      "    `CHNL_TXN_SER_NO`          varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '渠道交易流水号',\n"
      "    `ATH_TXN_SER_NO`           varchar(31) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '授权交易流水号',\n"
      "    `PENDG_POST_ATH_INR_ID`    varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '待入账授权内部编号',\n"
      "    `ATH_MSG_TP_CD`            varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '授权消息类型代码',\n"
      "    `TXN_STS_CD`               varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易状态代码',\n"
      "    `TXN_DES`                  varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin         DEFAULT NULL "
      "COMMENT '交易描述',\n"
      "    `OGLTXN_INR_ID`            varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '原交易内部编号',\n"
      "    `RLT_CDT_TXN_INR_ID`       varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联贷记交易内部编号',\n"
      "    `RLT_INSTM_TXN_INR_ID`     varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联分期交易内部编号',\n"
      "    `RLT_DISPT_TXN_INR_ID`     varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联争议交易内部编号',\n"
      "    `RLT_ON_ACCT_TXN_INR_ID`   varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联悬挂账交易内部编号',\n"
      "    `RLT_CCY_EXCH_FEE_INR_ID`  varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联货币兑换手续费内部编号',\n"
      "    `RLT_HDL_FEE_INR_ID`       varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '关联手续费内部编号',\n"
      "    `ORGL_CHNL_TXN_SER_NO`     varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '原渠道交易流水号',\n"
      "    `ORGL_ATH_TXN_SER_NO`      varchar(31) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '原授权交易流水号',\n"
      "    `DEBIT_ACRUD_AMT`          decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '借方发生额',\n"
      "    `CDT_ACRUD_AMT`            decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '贷方发生额',\n"
      "    `CDT_ADJ_AMT`              decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '贷方调整金额',\n"
      "    `BLUNIT_ASGN_LIST`         text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT "
      "'余额单元分配列表',\n"
      "    `WTEDOW_MINDUE_AMT_AMT`    decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '冲减最低应付款金额',\n"
      "    `TXN_INS_REDU_ACTY_CD`     varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易立减活动代码',\n"
      "    `BEF_INS_REDU_AMT`         decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '立减前金额',\n"
      "    `INS_REDU_AMT`             decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '立减金额',\n"
      "    `RMNG_SBSD_AMT`            decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '剩余补贴金额',\n"
      "    `RTN_INS_REDU_SBSD_AMT`    decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '扣回立减补贴金额',\n"
      "    `AUTO_BUY_EXCH_EXCH_RTE`   decimal(9, 5)                                                  DEFAULT NULL "
      "COMMENT '自动购汇汇率',\n"
      "    `EXCH_STLMT_AMT`           decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '已结汇金额',\n"
      "    `INSTM_SCSS_FLG`           char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '分期成功标志',\n"
      "    `INSTM_PROD_CD`            varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '分期产品代码',\n"
      "    `INSTM_AMT`                decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '分期金额',\n"
      "    `INSTM_ORG_CD`             char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '分期组织代码',\n"
      "    `OTH_CLRG_MATCH_CRITR`     varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '其他清算匹配准则',\n"
      "    `GMT_FMT_DT_AND_TME`       varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT 'GMT格式的日期和时间',\n"
      "    `ATH_DT`                   char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '授权日期',\n"
      "    `ATH_TME`                  char(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '授权时间',\n"
      "    `TXN_ATH_ENCDE`            varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易授权码',\n"
      "    `MCC`                      varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '商户类别代码',\n"
      "    `TXN_CTRY_CD`              char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '交易国家代码',\n"
      "    `TXN_CITY_CD`              varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易城市代码',\n"
      "    `TXN_CHNL_CD`              varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易渠道代码',\n"
      "    `MEDM_PROD_CD`             varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '介质产品代码',\n"
      "    `ASSET_ATTR_CD`            varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT '0' "
      "COMMENT '资产属性代码',\n"
      "    `SERH_REF_NO`              varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '检索参考号',\n"
      "    `CLOUD_CRD_NO`             varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '云卡卡号',\n"
      "    `CUP_MCC_SPCL_CRG_CD`      varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '银联MCC特殊计费代码',\n"
      "    `MICRO_EXMT_PSWD_FLG`      char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '小额免密标志',\n"
      "    `QR_CD_SCNE_TP_CD`         char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '二维码场景类型代码',\n"
      "    `CNTPR_FIN_INST_BCHNW_CD`  varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '对方金融机构网点代码',\n"
      "    `CTP_FININST_BCHNW_NME`    varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin         DEFAULT NULL "
      "COMMENT '对方金融机构网点名称',\n"
      "    `CNTPR_NME`                varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易对手名称',\n"
      "    `CNTPR_ACCT_NO`            varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易对手账号',\n"
      "    `CNTPR_ID_TP_CD`           varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '交易对手证件类型代码',\n"
      "    `CNTPR_ID_NO`              varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '交易对手证件号码',\n"
      "    `ACCT_CHKG_STAG_CD`        varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '账户核算阶段代码',\n"
      "    `CLCMCTL_FLG`              char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '催收管控标志',\n"
      "    `OVLMT_FLG`                char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '超限标志',\n"
      "    `OVLMT_RSN_CD`             varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '超限原因代码',\n"
      "    `OVLMT_AMT`                decimal(17, 0)                                                 DEFAULT NULL "
      "COMMENT '超限金额',\n"
      "    `INR_PROD_CD`              varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '内部产品代码',\n"
      "    `RECVG_BCH_NO`             char(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '受理分行号',\n"
      "    `EQTY_ID`                  varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '权益编号',\n"
      "    `ATH_MATCH_FLG`            char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '授权匹配标志',\n"
      "    `ACQRR_CD`                 varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '收单机构代码',\n"
      "    `TRMNL_NO`                 varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '终端号',\n"
      "    `PCS_CD`                   varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '处理码',\n"
      "    `SERV_SPOT_INPT_MTHD_CD`   varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '服务点输入方式代码',\n"
      "    `MERCH_ID`                 varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '商户编号',\n"
      "    `LV2_MCC`                  varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '二级商户类别代码',\n"
      "    `LV2_MERCH_ID`             varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '二级商户编号',\n"
      "    `LV2_MERCH_NME`            varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '二级商户名称',\n"
      "    `R36CYC_RPM_HISR`          varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '最近36个周期的还款历史',\n"
      "    `SYS_TRACE_AUDT_NO`        varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '系统追踪审计号',\n"
      "    `ACCT_CLCN_STS_CD`         char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '账户催收状态代码',\n"
      "    `ACCT_PROD_TP_CD`          char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '账产品类型代码',\n"
      "    `ANTI_MNYLADR_SBMSN_FLG`   char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '反洗钱报送标志',\n"
      "    `INTSTL_DAYRPL_BTW_TX_FLG` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '结息到日切间交易标志',\n"
      "    `INST_CD`                  char(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin              DEFAULT NULL "
      "COMMENT '机构代码',\n"
      "    `OPRT_ID`                  varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin          DEFAULT NULL "
      "COMMENT '操作员编号',\n"
      "    `OPR_DT`                   char(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin             DEFAULT NULL "
      "COMMENT '操作日期',\n"
      "    `BTCH_SEQ_NO`              int(6) DEFAULT NULL COMMENT '批次序号',\n"
      "    `OPR_FLG`                  char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin     NOT NULL DEFAULT 'E' "
      "COMMENT '操作标志',\n"
      "    `CRE_TMS`                  datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP (3) COMMENT '创建时间戳',\n"
      "    `CRE_USER_ID`              varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'SYSTEM' "
      "COMMENT '创建用户编号',\n"
      "    `CRE_CHNL_CD`              varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '创建渠道代码',\n"
      "    `UPDT_TMS`                 datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP (3) COMMENT '更新时间戳',\n"
      "    `UPDT_USER_ID`             varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'SYSTEM' "
      "COMMENT '更新用户编号',\n"
      "    `UPDT_CHNL_CD`             varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin           DEFAULT NULL "
      "COMMENT '变更渠道代码',\n"
      "    `REC_VERSN_NO`             int(8) NOT NULL DEFAULT '0' COMMENT '记录版本号',\n"
      "    PRIMARY KEY (`TXN_INR_ID`),\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_1` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, "
      "`RLT_INSTM_TXN_INR_ID`, `BSN_UNIT_NO`, `POST_DT`, `BAL_OBJ_CD`, `BAL_OBJ_TP_CD`, `DEBIT_CDT_TP`, "
      "`INSTM_SCSS_FLG`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_10` (`POST_DT`, `DEBIT_CDT_TP`, `BSN_TP_CD`, "
      "`DOM_OVS_FLG_CD`, `ATH_MATCH_FLG`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_2` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, `CARD_NO`, "
      "`CYC_NO`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_3` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, `CYC_NO`, "
      "`TXN_SEQ_NO`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_4` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, "
      "`ATH_TXN_SER_NO`, `ACQRR_CD`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_5` (`MAIN_CUST_INR_ID`, `CARD_NO`, `SYS_TRACE_AUDT_NO`, "
      "`ATH_TME`, `ACQRR_CD`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_7` (`MAIN_CUST_INR_ID`, `BSN_LYR_ACCT_NO`, `CYC_NO`, "
      "`TXN_STS_CD`, `CARD_NO`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_8` (`POST_DT`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_9` (`MAIN_CUST_INR_ID`, `CUST_INR_ID`, "
      "`PENDG_POST_ATH_INR_ID`) BLOCK_SIZE 16384 LOCAL,\n"
      "    KEY                        `ac_txn_sumry_tmp_ix_11` (`CHNL_TXN_SER_NO`) BLOCK_SIZE 16384 LOCAL\n"
      ") DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 3 BLOCK_SIZE = 16384 "
      "USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0\n"
      " partition by key(txn_inr_id)xxxxx\n;";
  std::string result;
  int ret = sql_parser.parse(origin, result);
  ASSERT_EQ(OMS_FAILED, ret);
  ASSERT_EQ("", result);
}

TEST(DDLParser, create_database)
{
  oceanbase::binlog::DdlParser sql_parser;
  Config::instance().binlog_ddl_convert_jvm_options.set("-Djava.class.path=./deps/lib/"
                                                        "etransfer.jar|-Xmx256M|-Xtrace|-XX:+CreateMinidumpOnCrash");
  sql_parser.init();
  std::string origin = "create database obcdc_db;";
  std::string result;
  int ret = sql_parser.parse(origin, result);
  ASSERT_EQ(OMS_FAILED, ret);
  ASSERT_EQ("", result);
}

TEST(DDLParser, drop_table)
{
  oceanbase::binlog::DdlParser sql_parser;
  Config::instance().binlog_ddl_convert_jvm_options.set("-Djava.class.path=./deps/lib/"
                                                        "etransfer.jar|-Xmx256M|-Xtrace|-XX:+CreateMinidumpOnCrash");
  sql_parser.init();
  std::string origin = "DROP TABLE `test`.`test005`";
  std::string result;
  int ret = sql_parser.parse(origin, result);
  ASSERT_EQ(OMS_OK, ret);
  //  ASSERT_EQ("", result);
}
#endif
